substance_ind_list: [0, 1, 2, 3]

# basis_func_ind_list: [0, 1, 2, 3, 4, 5, 6]
basis_func_ind_list: [0, 1, 4, 6]
num_bf: 4

temp_K_list: 
  start: 253.15
  stop: 303.15
  step: 10
  # Or to use a predefined list, uncomment below:
  values: [293.15]

train_noise:
  start: 0
  stop: 2.0
  step: 0.2
  # Or to use a predefined list, uncomment below:
  values: [0]
  

test_noise:
  start: 0
  stop: 2.0
  step: 0.2
  # Or to use a predefined list, uncomment below:
  values: [0]


air_refractive_index: 1
atm_dist_ratio: 0.11
percentage_step: 0.05


train_percentage: 0.8
batch_size: 500
loss_func_names: ['L1Loss', 'MSELoss']
learning_rate: 2.0e-3
num_epochs: 300
device: cpu
k_fold_flag: true
k: 5
random_flag: true
random_seed: 28

confidence: 0.95

# drop_duplicates_columns: ['Temperature_K', 'Substance Number', 'Substance Comb', 'Basis Function Number', 'Basis Function Comb', 'Train Noise']
drop_duplicates_columns_num: -2

file_paths:
  air_trans_file: './data/Test 3 - 4 White Powers/Air transmittance.xlsx'
  basis_func_file: './data/Test 3 - 4 White Powers/Basis functions_4-20um.xlsx'
  spectra_file: './data/Test 3 - 4 White Powers/white_powders_spectra.xlsx'
  substances_emit_file: './data/Test 3 - 4 White Powers/white_powders.xlsx'
  substance_names_file: './data/Test 3 - 4 White Powers/white_powders_names.xlsx'

output_folder: './output'
output_file_name: 'trained_models_unknown_sub'